<a href="https://colab.research.google.com/github/syilmazs/Pandas/blob/main/Assignment_1_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [2]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [3]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [4]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [5]:
a = np.ones([4,4], dtype=int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [6]:
a*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [7]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [8]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [9]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [10]:
np.linspace(0, 25, 25, endpoint=False, dtype=int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [11]:
np.random.rand(5)

array([0.9568705 , 0.80679272, 0.9886624 , 0.21167744, 0.49218551])

#### 11. Create random normal distributed 5x5 array

In [12]:
np.random.randn(5,5)

array([[ 1.30101939, -0.3394601 , -0.51280104,  0.78923633,  0.14579049],
       [-0.31923675, -1.94142803, -0.22823197,  2.46978748,  0.21903334],
       [ 0.21032891, -0.51999053, -0.59070558, -0.83275548,  0.08721577],
       [ 1.37290371, -0.42080752, -1.82387755, -0.90776033, -1.71702438],
       [ 0.80690048, -0.43088362,  0.80710173,  1.29042109,  1.42031235]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [13]:
np.random.randint(20,50, size=(3,4))

array([[47, 46, 27, 39],
       [39, 48, 31, 22],
       [23, 45, 36, 42]])

#### 13. Reshape the array below with shape 6x8

In [14]:
ranarr = np.random.randint(0, 60, 48)

In [15]:
np.reshape(ranarr, (6,8))

array([[22, 11, 17,  8, 37, 16, 28, 10],
       [23, 55, 22, 46, 56, 34, 43,  5],
       [ 4, 33, 29, 22, 44, 30,  4, 57],
       [11, 14, 48, 55, 36,  7, 13, 25],
       [ 5, 37, 18,  7, 26, 35, 43, 54],
       [49, 23,  4, 41, 33, 24, 36, 19]])

In [16]:
ranarr

array([22, 11, 17,  8, 37, 16, 28, 10, 23, 55, 22, 46, 56, 34, 43,  5,  4,
       33, 29, 22, 44, 30,  4, 57, 11, 14, 48, 55, 36,  7, 13, 25,  5, 37,
       18,  7, 26, 35, 43, 54, 49, 23,  4, 41, 33, 24, 36, 19])

In [17]:
ranarr.reshape(6,8)

array([[22, 11, 17,  8, 37, 16, 28, 10],
       [23, 55, 22, 46, 56, 34, 43,  5],
       [ 4, 33, 29, 22, 44, 30,  4, 57],
       [11, 14, 48, 55, 36,  7, 13, 25],
       [ 5, 37, 18,  7, 26, 35, 43, 54],
       [49, 23,  4, 41, 33, 24, 36, 19]])

In [18]:
#reshape with -1

In [19]:
ranarr.reshape(-1,8)

array([[22, 11, 17,  8, 37, 16, 28, 10],
       [23, 55, 22, 46, 56, 34, 43,  5],
       [ 4, 33, 29, 22, 44, 30,  4, 57],
       [11, 14, 48, 55, 36,  7, 13, 25],
       [ 5, 37, 18,  7, 26, 35, 43, 54],
       [49, 23,  4, 41, 33, 24, 36, 19]])

## Numpy Indexing and Selection


In [20]:
#Create array below
arr2=np.arange(1,21,3)
arr2

array([ 1,  4,  7, 10, 13, 16, 19])

In [21]:
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [22]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [23]:
mat[:,0:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

#### 16. Get the values in 2nd row for every 2 step.

In [24]:
mat[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [25]:
mat[:,2:3]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [26]:
mat[[0,2],[0,1]]

array([ 1, 10])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [27]:
mat[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [28]:
toplam = mat[mat<10]+mat[mat>12]

#### 21. Get the standard deviation of the result above

In [29]:
np.std(toplam)

29.700546274093877

#### 22. Get the sum of second column from array above

In [30]:
#print array here

In [31]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [32]:
np.sum(mat[::,1:2])

32

#### 23. Get the median,mean and std of 3rd row from array above

In [33]:
#median

In [34]:
np.median(mat[2])

11.0

In [35]:
#mean

In [36]:
np.mean(mat[2])

27.0

In [37]:
#std

In [38]:
np.std(mat[2])

28.88771365130858

# Pandas Section

In [39]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [40]:
df = pd.read_csv("Salaries.csv")

In [41]:
df

Id       EmployeeName  ...         Agency  Status
0            1     NATHANIEL FORD  ...  San Francisco     NaN
1            2       GARY JIMENEZ  ...  San Francisco     NaN
2            3     ALBERT PARDINI  ...  San Francisco     NaN
3            4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4            5    PATRICK GARDNER  ...  San Francisco     NaN
...        ...                ...  ...            ...     ...
148649  148650      Roy I Tillery  ...  San Francisco     NaN
148650  148651       Not provided  ...  San Francisco     NaN
148651  148652       Not provided  ...  San Francisco     NaN
148652  148653       Not provided  ...  San Francisco     NaN
148653  148654          Joe Lopez  ...  San Francisco     NaN

[148654 rows x 13 columns]

In [42]:
df.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [43]:
df.sample()

Id  EmployeeName       JobTitle  ...  Notes         Agency  Status
60673  60674  Chinelo Amah  Special Nurse  ...    NaN  San Francisco     NaN

[1 rows x 13 columns]

In [44]:
df.tail()

Id   EmployeeName  ...         Agency  Status
148649  148650  Roy I Tillery  ...  San Francisco     NaN
148650  148651   Not provided  ...  San Francisco     NaN
148651  148652   Not provided  ...  San Francisco     NaN
148652  148653   Not provided  ...  San Francisco     NaN
148653  148654      Joe Lopez  ...  San Francisco     NaN

[5 rows x 13 columns]

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [46]:
df.describe()

Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [47]:
df.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [48]:
df.size

1932502

**Print out max and avg Totalpay**

In [49]:
#max

In [50]:
df["TotalPay"].max()

567595.43

In [51]:
#avg

In [52]:
df["TotalPay"].mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [53]:
len(df[df["TotalPay"]>df["TotalPay"].mean()])

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [54]:
df[df["EmployeeName"]=="ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [55]:
df[df["TotalPay"] == df["TotalPay"].min()]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [56]:
df["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [57]:
df["JobTitle"].value_counts().tail(3)

SHELTER OFFICE ASSISTANT SUPERVISOR    1
Musm Exhibit Packer & Repairer         1
CHIEF HOUSING INSPECTOR                1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [58]:
len(df[df["Year"]==2012])

36766

In [59]:
len(df[df.TotalPayBenefits>df.TotalPayBenefits.mean()])

73004

In [60]:
len(df[df["TotalPayBenefits"]>df["TotalPayBenefits"].mean()][df["Year"]==2012])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


20366

In [61]:
df[(df.TotalPayBenefits>df.TotalPayBenefits.mean()) & (df.Year==2012)]['EmployeeName'].count()

20366

**How many people have the word Manager in their job title?**

In [62]:
#use apply function here

In [107]:
def manager_func(x):
  if "manager" in x.lower():
    return True
  else:
    return False

len(df[df["JobTitle"].apply(lambda x:manager_func(x))])

4110

In [108]:
len(df[df["JobTitle"].apply(lambda x: True if "manager" in x.lower() else False)])

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [96]:
sal_new2= df.iloc[:, [0,1,2,7,8]]
sal_new2

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [94]:
sal_new = df.loc[:,"EmployeeName":"TotalPayBenefits"]
sal_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 8 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [80]:
df[(df["TotalPayBenefits"]>df["TotalPayBenefits"].min())&(df["TotalPayBenefits"]<df["TotalPayBenefits"].mean())]["EmployeeName"]


10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object